In [54]:
import numpy as np

In [62]:
number = np.random.randint(1,1000, 10000)

In [63]:
number

array([975, 230, 395, ..., 180, 176, 147])

In [64]:
mat = number[:,None]

In [65]:
mat

array([[975],
       [230],
       [395],
       ...,
       [180],
       [176],
       [147]])

In [66]:
final_result = (mat - number)/np.maximum(mat,number)

In [67]:
final_result.shape

(10000, 10000)

In [60]:
final_result

array([[ 0.        ,  0.11111111,  0.88888889,  0.77777778,  0.77777778],
       [-0.11111111,  0.        ,  0.875     ,  0.75      ,  0.75      ],
       [-0.88888889, -0.875     ,  0.        , -0.5       , -0.5       ],
       [-0.77777778, -0.75      ,  0.5       ,  0.        ,  0.        ],
       [-0.77777778, -0.75      ,  0.5       ,  0.        ,  0.        ]])